name: Go test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test
